train_config:
  batch_size: 6
  epochs: 22000
  lr: 0.000001
  device: cuda
  ckpt_dir: ./checkpoints/siggraph_new/last_0

  summon_ckpt: true
  accumulation_steps: 1
  save_period: 1000
  max_saves: 5

eval_config:
  lr: 0.000001
  eval_period: 6
  batch_size: 1

log_config:
  log_dir: siggraph_new
  log_period_loss: 20
  log_period_visual: 500

test_config:
  batch_size: 8
  num_samples: 8

  log_period_visual: 500
  log_period_loss: 100
