train_config:
  batch_size: 8
  epochs: 22000
  lr: 0.000002
  device: cuda
  ckpt_dir: ./checkpoints/albedo/train_9000

  summon_ckpt: true
  accumulation_steps: 1
  save_period: 1000
  max_saves: 5

eval_config:
  lr: 0.000001
  eval_period: 6
  batch_size: 4

log_config:
  log_dir: albedo
  log_period_loss: 20
  # log_period_visual: 100
  log_period_visual: 1000

test_config:
  batch_size: 8
  num_samples: 8

  # log_period_visual: 100
  log_period_visual: 1000
  log_period_loss: 100
